### ISSUE TITLE
[Desktop] image not cropped and in low quality

### ISSUE THREAD

**Issue by andreschab90** [remedyMatch/rm-landingpage#15]
The image for the press article at https://www.zukunft-krankenhaus-einkauf.de/ is not cropped and in low quality

<img width="674" alt="Bildschirmfoto 2020-03-28 um 18 55 08" src="https://user-images.githubusercontent.com/24413222/77830062-23b54680-7126-11ea-86ad-a20b7f0ca630.png">

The cropping looks good in a mobile browser, but image quality is low as well

**Comment by vMarkus** [comment]
taken from original website, image source https://image.jimcdn.com/app/cms/image/transf/dimension=412x10000:format=jpg/path/s6bc74607d9754aff/image/i01acc34bbea4b38a/version/1582116184/image.jpg

@skyrun2001 can you do the exchange?
![zukunft-krankenhaus-einkauf](https://user-images.githubusercontent.com/44782615/78339100-3dc2af00-7594-11ea-96a2-8276ce756857.jpg)
