### ISSUE TITLE
not clear that page contains more content

### ISSUE THREAD

**Issue by andreschab90** [remedyMatch/rm-landingpage#20]
The page doesn't inform the user, that there is more content to discover.
Issue occurs on denktop and mobile clients
<img width="1914" alt="Bildschirmfoto 2020-03-29 um 21 48 05" src="https://user-images.githubusercontent.com/24413222/77859028-4e2b0080-7207-11ea-811a-a752419620be.png">

**Comment by skyrun2001** [comment]
Changed CSS, now it is visible again
![image](https://user-images.githubusercontent.com/59117040/78340702-cf332080-7596-11ea-81f9-88c3b79a5034.png)
