### ISSUE TITLE
Presse-Seite erstellen

### ISSUE THREAD

**Issue by roman-1983** [remedyMatch/rm-landingpage#27]
Da wir mittlerweile ein paar Presse-Erwähnungen haben, sollten wir eine Unterseite für Presse-Erwähnungen einrichten.

# Technische Beschreibung
- Erstellen einer Unterseite "Presse"
- Anzeigen der 5 neuesten Presse-Erwähnungen im Slider
- Link unter dem Slider auf die Presse-Seite
- Link im Footer auf die Presse-Seite
- Auf der Presse Seite alle Presse-Erwähnungen in einer Galerie, nach Datum sortiert
- Auf der Presse-Seite ein weiterer Abschnitt "Presse-Mappe" & Ansprechpartner

**Comment by skyrun2001** [comment]
Beginn des Entwurfs in branch feature/27-presse-seite

**Comment by skyrun2001** [comment]
Alles bis auf die Pressemappe ist angelegt
