### ISSUE TITLE
Unterseite "Jobs"

### ISSUE THREAD

**Issue by roman-1983** [remedyMatch/rm-landingpage#29]
Es soll eine Unterseite "Jobs" geben, bei der wir Stellenangebote ausschreiben können.

# Technische Beschreibung
- Unterseite anlegen
- Im Footer verlinken
- Einleitungstext mit Marketing abstimmen
- Position mit HR abstimmen

**Comment by roman-1983** [comment]
Seite wurde erstellt: https://remedymatch.io/jobs

**Comment by skyrun2001** [comment]
Email wurde von hr@remedymatch.io temporär auf info@remedymatch.io geändert. Muss später zurückgesetzt werden

**Comment by skyrun2001** [comment]
Added a Disclaimer to jobs
