### ISSUE TITLE
Registrierung anpassen

### ISSUE THREAD

**Issue by roman-1983** [remedyMatch/rm-landingpage#35]
Es gibt derzeit keine umfangreiche Validierung für die Felder bei der Registrierung. Folgende Validierungen sollen eingebaut werden.

# Technische Beschreibung
- Telefon Feld wird offenbar nicht geprüft, eine Ziffer reicht hier schon zum weiterklicken bei diesem Pflichtfeld. RegEx Beispiel zur Prüfung internationaler Telefonnummer: https://www.oreilly.com/library/view/regulare-ausdrucke-kochbuch/9783868993219/ch04s03.html 
- PLZ frisst auch nur eine Ziffer anstelle der nötigen 5. Postalcode Validator z. B. für PHP hier https://packagist.org/packages/fadoe/postalcode-validator (edited) 
- Straßenname akzeptiert auch nur einen Buchstaben als Pflichtfeld - könnte evtl auch durch Postfach von Instituten gefüllt sein
- Persönliche Daten: "Art der Organisation" ist kein Pflichtfeld und kann leer bleiben - bei Orga sollte das ein Pflichtfeld sein für qualifizierte Daten

**Comment by skyrun2001** [comment]
Review abgeschlossen. Code bereits ausgerollt.
