### ISSUE TITLE
Partner & Sponsoren-Bereich anlegen

### ISSUE THREAD

**Issue by roman-1983** [remedyMatch/rm-landingpage#5]
Es soll einen Partner & Sponsoren-Bereich geben.

**Comment by skyrun2001** [comment]
**Beginn der Rohfassung.**
Erstellt ist ein Copy and Paste Area, welche für jeden Sponsor kopiert werden kann und angepasst werden kann. Bisher noch kein Visual test durchgeführt und erstmal nur ein Partner/ Sponsor zur Probe eingebunden.

 **TODO:** 

- [ ] Prüfen ob alles stimmt

- [ ] Texte anpassen

- [ ] alle sponsoren zusammentragen und eintragen
