### ISSUE TITLE
Slogan im Header nicht responsive

### ISSUE THREAD

**Issue by roman-1983** [remedyMatch/rm-landingpage#8]
Der Slogan im Header ist nicht responsive und wird auf Mobilgeräten viel zu groß angezeigt.
Ich habe den Slogan manuell eingebaut und nutze dafür bisher nicht 🙈die Bootstrap-Klassen, vielleicht liegt es ja daran?

![image](https://user-images.githubusercontent.com/3573021/77452431-395d0000-6df6-11ea-8184-b32a79d3f99b.png)

**Comment by skyrun2001** [comment]
Done!
