### ISSUE TITLE
Responsive - Kein Menü anzeigen

### ISSUE THREAD

**Issue by roman-1983** [remedyMatch/rm-landingpage#9]
Solange wir keine Unterseiten haben, kann das Menü versteckt werden.

Bzw. wäre es besser, wenn die Social-Icons nicht im Markup vom Menü sind, sondern vielleicht in einer eigenen Navigation neben dem eigentlichen Menü angezeigt werden.

**Comment by skyrun2001** [comment]
Hat sich das Ticket erledigt?
